[package]
name = "mux"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
path = "src/mux.rs"

[dependencies]
regex.workspace = true
mux_protocol = { workspace = true }
nanoid = { workspace = true }
prost = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
dirs = { workspace = true }
tar = "0.4"
flate2 = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-channel = "2.3"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
interprocess = { workspace = true }
smol = "1.3"
tokio = { workspace = true, features = ["rt", "process", "io-util", "time", "macros"], optional = true }
tempfile = { workspace = true, optional = true }
which = { workspace = true, optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
gloo-timers = { version = "0.3", features = ["futures"] }
getrandom = { version = "0.3.4", features = ["wasm_js"] }
getrandom02 = { package = "getrandom", version = "0.2", features = ["js"] }

[features]
ssh = ["dep:tokio", "dep:tempfile", "dep:which"]

[dev-dependencies]
async-channel = "2.3"
tempfile = { workspace = true }
interprocess = { workspace = true, features = ["tokio"] }
serde_json = "1.0"
tokio = { workspace = true, features = ["full"] }
mux_protocol = { workspace = true }
terminal_view = { workspace = true }
