#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 [production|staging|...]"
  exit 1
fi

export ZERMINAL_KUBE_NAMESPACE=$1

pod=$(kubectl --namespace=${ZERMINAL_KUBE_NAMESPACE} get pods --selector=app=zed --output=jsonpath='{.items[*].metadata.name}')
exec kubectl --namespace $ZERMINAL_KUBE_NAMESPACE exec --tty --stdin $pod -- /bin/bash
